#!/usr/bin/env bun
import { readdir } from 'node:fs/promises';
import { join, resolve } from 'node:path';

/**
 * Regenerate `embedded-payload.generated.ts` from the `skills/` directory.
 *
 * Why this exists: `doctor` finds the packaged skills through the package
 * directory, which `bun build --compile` does not expose — the compiled binary
 * resolves `import.meta.dirname` *inside* the bundle, so the payload is not on
 * the filesystem and the skills gate always reported it missing. Embedding the
 * files in the bundle makes the binary genuinely self-contained.
 *
 * Two rules keep the embedded copy honest:
 *
 * 1. **The filesystem wins at runtime.** `doctor` prefers a readable package
 *    directory and only falls back to this copy, so editing a skill in a source
 *    checkout takes effect immediately, with no regeneration step.
 * 2. **A test asserts the two agree.** `tests/embedded-payload.test.ts` fails if
 *    this file and `skills/` ever diverge, so a stale embed cannot ship silently.
 *
 * Run via `bun run generate:payload`, which `build:cli` does first.
 */

const PACKAGE_ROOT = resolve(import.meta.dirname, '..');
const SKILLS_DIR = join(PACKAGE_ROOT, 'skills');
const OUTPUT = join(PACKAGE_ROOT, 'src', 'apps', 'doctor', 'embedded-payload.generated.ts');

/** Must match `SKILL_NAMES` in the doctor module. */
const SKILL_NAMES = ['montflow-create-pi-skills', 'montflow-modify-pi-skills'] as const;

const readSkill = async (name: string): Promise<Record<string, string>> => {
  const dir = join(SKILLS_DIR, name);
  const entries = (await readdir(dir)).filter((entry) => !entry.startsWith('.')).toSorted();
  const files: Record<string, string> = {};
  for (const entry of entries) {
    files[entry] = await Bun.file(join(dir, entry)).text();
  }
  return files;
};

const main = async (): Promise<void> => {
  const payload: Record<string, Record<string, string>> = {};
  for (const name of SKILL_NAMES) {
    const files = await readSkill(name);
    if (files['SKILL.md'] === undefined) {
      throw new Error(`skill '${name}' has no SKILL.md — refusing to generate`);
    }
    payload[name] = files;
  }

  // Plain JSON, not hand-rolled object syntax: the file is exempt from
  // `oxfmt` and `oxlint` via `**/*.generated.ts`, so regenerating produces no
  // spurious diff, and `JSON.stringify` handles every escaping case for free.
  const body = `/**
 * DO NOT EDIT — generated by \`bun run generate:payload\`.
 *
 * The packaged skills, embedded verbatim so the \`mf-skills\` binary is
 * self-contained under \`bun build --compile\`, where the package directory does
 * not exist at runtime. \`doctor\` prefers a readable package directory and
 * falls back to this copy; \`tests/embedded-payload.test.ts\` fails if the two
 * ever diverge.
 *
 * Source: \`skills/\`
 */
export const EMBEDDED_SKILL_PAYLOAD: Readonly<Record<string, Readonly<Record<string, string>>>> = ${JSON.stringify(payload, null, 2)};
`;

  await Bun.write(OUTPUT, body);
  const bytes = Object.values(payload).reduce(
    (total, files) => total + Object.values(files).reduce((sum, text) => sum + text.length, 0),
    0,
  );
  console.log(
    `wrote ${OUTPUT.replace(PACKAGE_ROOT, '.')} — ${SKILL_NAMES.length} skills, ${bytes} bytes of payload`,
  );
};

await main();
